### ISSUE TITLE
Long waiting auto disconnect?

### ISSUE THREAD

**Issue by rockyliu520** [dingmaotu/mql4-redis#10]
I am currently using this library to listen to a specified channel, but after long waiting (no message sent to channel). The Mt4 redis will automatically disconnect? Any idea? I have configed the redis server set no timeout on connection.

**Comment by dingmaotu** [comment]
The Redis client must keep the connection alive by sending messages to the server. I don't know if there is a keep alive option just like http, but it is how a tcp connection works.

**Comment by rockyliu520** [comment]
Ok thanks for your answer. Currently I just keep the redis in mt4 sending trash message to a useless channel, the same as on subscribe end.
