### ISSUE TITLE
How can I confirm my env match vs2015 runtime?

### ISSUE THREAD

**Issue by janckerchen** [dingmaotu/mql4-redis#2]
On my winserver 2012,  mt4 cant load dll.

![screenshot of parallels desktop 2017 4 20 21 46](https://cloud.githubusercontent.com/assets/68181/25233905/046e444a-2613-11e7-808b-c83fe062b68c.png)

How can I confirm my env match vs2015 runtime?

**Comment by janckerchen** [comment]
Installing [Visual C++ Redistributable for Visual Studio 2015
](https://www.microsoft.com/en-us/download/details.aspx?id=48145) fix this problem.

Mt4Redis.dll load successfuully, but  another problem arised.

![screenshot of parallels desktop 2017 4 20 21 54](https://cloud.githubusercontent.com/assets/68181/25234287/37c28ed6-2614-11e7-94a6-68ef54f264d3.png)

**Comment by janckerchen** [comment]
any help?

```
2017.05.05 08:13:38.474	TestRedisSimple XAUUSD,M30: Mt4Redis Error: 系统试图将驱动器合并到合并驱动器上的目录。
```

**Comment by dingmaotu** [comment]
@janckerchen This is weird. The error message seems not related to Redis. Can you give me a detailed error report, such as which import function caused the error?

And since you are using windows server, are you using remote desktop and mapping some local resources to the server? You can try this on you local computer to see if this error still occurs.

**Comment by janckerchen** [comment]
I  located the error message showed up at RedisContext.mqh:85

```
RedisContext *RedisContext::connect(string ip,int port,int seconds,int microseconds)
  {
   int c= mt4RedisConnect(ip,port,seconds,microseconds);
   if(c == 0)
     {
      ....
     }
   else
     {
      int err= mt4RedisError(c);
      if(err!=REDIS_OK)
        {
         int buf;
85:   string res=mt4RedisErrorString(c,buf);  <---  ** looks here, res is the error desc ***
         if(buf>0)
         .....
  }
```

I use ParallelsDesktop virtual machine other than remote destop. How can it be effected redis  confused  me.

**Comment by dingmaotu** [comment]
There might be some configuration error in your redis server or client connection parameters. I don't know the exact reason, but I found following links being helpful:

https://forums.openvpn.net/viewtopic.php?t=21330
https://forum.acevpn.com/vpn_postst4279_The-system-tried-to-join-a-drive-to-a-directory-on-a-joined-drive.aspx
https://epochmod.com/forum/topic/35271-redis-server-not-reachable/

All these pages is somewhat related to winsock connection problems. But none gives the exact reason. I can only guess some possible reasons. First ensure your redis server is up and the address and port are correct in your client code. Ensure you can connect to the redis server with a redis cli client on Windows guest if your server is running in your Mac host.The virtual machine network interface might also be the problem; do try the same code on a real Windows machine and see if the error occurs.

**Comment by janckerchen** [comment]
@dingmaotu thanks your infomation~.  Finally I find the anwser,  the redis installed by homebrew is only binded to 127.0.0.1 by default.  So I changed the redis.conf and add `bind <my remote ip>`, it works,  connected from parallels to mac.

thanks agian,  it's useful tool to professional mql programmer.

**Comment by traddo** [comment]
This error also occurs when redis server is down.
