### ISSUE TITLE
How to use appendCommand?

### ISSUE THREAD

**Issue by janckerchen** [dingmaotu/mql4-redis#3]
`appendCommand()` has no return,  should I invoke other method after several `appendCommand()` to trigger context execution?  is it `getReply()` ?

**Comment by dingmaotu** [comment]
Yes, `getReply` will send all appended commands, and get a list of replies corresponding each command. Be careful extracting results from reply, it may be nested lists.

**Comment by janckerchen** [comment]
I wanna sync all orders info to redis,  which api you recommend, maybe `Redis::hset` or `Redis::hmset`, there is no example  for the usage of Redis.mqh

**Comment by dingmaotu** [comment]
hmset would be better, but a single hmset only sets one order, you need a loop to set all orders.

Redis.mqh is added as a convenient wrapper of commonly used commands. I add this module after the main lib was finished, so no examples or docs. However, once you grasp basic commands, you can reference official Redis doc for how those commands can be used.

Have a look at `Scripts/Test/TestRedisSimple.mq4`, Redis.mqh basically follows the same structure and convention.
