### ISSUE TITLE
Do your consider to implement mql4-mongodb?

### ISSUE THREAD

**Issue by janckerchen** [dingmaotu/mql4-redis#5]
Mongodb  works better for complex data.

**Comment by dingmaotu** [comment]
Not this year... First, I am busy working on a complex EA and improving mql4-lib, so I might not have time to do this. Second, I do not have much experience with mongodb. I know it is a document store with JSON as the main data type. At least in MQL, JSON serialization/deserialization is not easy. Maybe I will first add JSON support to mql4-lib before doing this.

Recently I have plans for sqlite3, the lightweight SQL engine. It is in early stage, and once complete I will put it here. If you are interested, stay tuned to my github 😄

**Comment by janckerchen** [comment]
thanks for your  amazing jobs,  it's heavy,  valuble and generous.

Except your sqlite3 binding.   Btw,  are you independent trader or working in company?
