### ISSUE TITLE
Can you upload the dll source code? 

### ISSUE THREAD

**Issue by symis84** [dingmaotu/mql4-redis#6]
Thanks for what you did. The community appreciate it.
I would like to compile the dll also for MT4/MT5 64bit version, can you upload the dll source code.

Thanks so much
Simone

**Comment by dingmaotu** [comment]
Hi, thank you for your interest but current version of the DLL is not open source and will be deprecated. It's source is specifically written for MT4 without 64 bit compatibility in mind.

I am going to eliminate this closed source part by re-implementing the Redis protocol in MQL or by using a thin wrapper DLL of hiredis (this will be open sourced). My other bindings (like mql-zmq and mql-sqlite3) are MQL4/5 compatible, with 32/64 bit DLLs from the official source. This **mql4-redis** will be replaced by **mql-redis** with a similar structure.

**Comment by symis84** [comment]
Thanks for the answer. I will wait for the new version **mql-redis**

**Comment by kenorb** [comment]
> I am going to eliminate this closed source part by re-implementing the Redis protocol in MQL or by using a thin wrapper DLL of hiredis (this will be open sourced).

Any update?
