### ISSUE TITLE
just one issue:   do operate with redis  in indicator would slow down the terminal response

### ISSUE THREAD

**Issue by raidsan** [dingmaotu/mql4-redis#8]
Does a  async client api solution exists? 
The sync client api suit used in EA ,  mt4 EA runs on separate thread, and indicator is not.

**Comment by dingmaotu** [comment]
There is an async version of hiredis but there is not an elegant solution to make callbacks to EA or Indicator. It depends on what kind of operations you use. Generally most redis operations are very fast and the sync client should not be the bottleneck if used in an indicator.
