### ISSUE TITLE
Cannot load Mt4Redis.dll

### ISSUE THREAD

**Issue by rockyliu520** [dingmaotu/mql4-redis#9]
Any ideas on what happen to this?

Cannot call 'Mt4Redis.dll::mt4RedisConnect', 'Mt4Redis.dll' is not loaded
'C:\Users\Administrator\AppData\Roaming\MetaQuotes\Terminal\14AD9ECF74C435BB594645D98FA64433\MQL4\Libraries\Mt4Redis.dll' [193]

All the redis libraries are in right location.

![Mt4redis](https://user-images.githubusercontent.com/8691916/55701552-fe13c680-5a16-11e9-80bc-c631b2e6ace6.JPG)

![3232](https://user-images.githubusercontent.com/8691916/55701581-1aaffe80-5a17-11e9-9a28-353cc9bad2f2.JPG)

**Comment by dingmaotu** [comment]
Ensure that you have: 1. correct architecture: x86 vs x64; 2. correct version of vc++ runtime

**Comment by rockyliu520** [comment]
Thanks it works for me.
